version: '3.8'

services:
  todo-app:
    image: namchamchi/todo-app:latest
    container_name: todo-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=staging
    restart: unless-stopped
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge 